### ISSUE TITLE
on server loading 

### ISSUE THREAD

**Issue by tiarnia** [faceofcat/Tesla-Powered-Thingies#2] opened 2017-07-08 15:31 UTC
using newest versions of everything

server won't start

---- Minecraft Crash Report ----

WARNING: coremods are present:
  ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.0.1.jar)
  LibLoader (# LibLoader.jar)
  FullscreenFix (gud_fullscreen_fix-1.0.2 (1).jar)
  AppleCore (AppleCore-mc1.12-2.2.1.jar)
  CoreMod (TickProfiler-1.12-jenkins.12.jar)
  ForgelinPlugin (Forgelin-1.5.0.jar)
  LoadingPlugin (Quark-r1.2-100.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63+dev.98.jar)
  LoadingPlugin (RandomThings-MC1.12-4.0.2.jar)
Contact their authors BEFORE contacting forge

// Everything's going to plan. No, really, that was supposed to happen.

Time: 7/8/17 9:30 AM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Tesla Powered Thingies (teslathingies)
Caused by: java.lang.NoClassDefFoundError: net/ndrei/teslacorelib/items/gears/GearIronItem
	at net.ndrei.teslapoweredthingies.machines.fluidburner.FluidBurnerBlock.getRecipe(FluidBurnerBlock.kt:33)
	at net.ndrei.teslacorelib.blocks.RegisteredBlock.getRecipes(RegisteredBlock.kt:45)
	at net.ndrei.teslacorelib.blocks.RegisteredBlock.registerRecipe(RegisteredBlock.kt:36)
	at net.ndrei.teslacorelib.annotations.AutoRegisterRecipesHandler$1.invoke(handlers.kt:24)
	at net.ndrei.teslacorelib.annotations.AutoRegisterRecipesHandler$1.invoke(handlers.kt:20)
	at net.ndrei.teslacorelib.annotations.BaseAnnotationHandler.process(BaseAnnotationHandler.kt:41)
	at net.ndrei.teslacorelib.annotations.HandlersKt.processInitAnnotations(handlers.kt:92)
	at net.ndrei.teslacorelib.BaseProxy.init(proxies.kt:31)
	at net.ndrei.teslapoweredthingies.TeslaThingiesMod.init(TeslaThingiesMod.kt:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:628)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:252)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:230)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:781)
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:107)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:340)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:216)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:483)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: net.ndrei.teslacorelib.items.gears.GearIronItem
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 44 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_112, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 69848440 bytes (66 MB) / 567070720 bytes (540 MB) up to 6106120192 bytes (5823 MB)
	JVM Flags: 8 total; -XX:PermSize=256M -XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:+CMSClassUnloadingEnabled -XX:ParallelGCThreads=2 -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -Xmx6024M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.40 Powered by Forge 14.21.1.2402 76 mods loaded, 76 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UCHI	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{8.0.99.99} [Forge Mod Loader] (forgemod.jar) 
	UCHI	forge{14.21.1.2402} [Minecraft Forge] (forgemod.jar) 
	UCHI	gud_fullscreen_fix{} [Fullscreen Fix] (minecraft.jar) 
	UCHI	actuallyadditions{1.12-r113} [Actually Additions] (ActuallyAdditions-1.12-r113.jar) 
	UCHI	applecore{2.2.1} [AppleCore] (AppleCore-mc1.12-2.2.1.jar) 
	UCHI	jei{4.7.1.69} [Just Enough Items] (jei_1.12-4.7.1.69.jar) 
	UCHI	appleskin{1.0.7} [AppleSkin] (AppleSkin-mc1.12-1.0.7.jar) 
	UCHI	morphtool{1.2-15} [Morph-o-Tool] (Morph-o-Tool-1.2-15.jar) 
	UCHI	psi{r1.1-50} [Psi] (Psi-r1.1-50.jar) 
	UCHI	quark{r1.2-100} [Quark] (Quark-r1.2-100.jar) 
	UCHI	autoreglib{1.3-13} [AutoRegLib] (AutoRegLib-1.3-13.jar) 
	UCHI	bedbugs{@VERSION@} [Bed Bugs] (BedBugs-1.12-1.0.1.jar) 
	UCHI	betterbedrockgen{6.0.1} [BetterBedrockGen] (BetterBedrockGenerator-1.12-6.1.0.jar) 
	UCHI	betterbuilderswands{0.11.1} [Better Builder's Wands] (BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar) 
	UCHI	bibliocraft{2.4.2} [BiblioCraft] (BiblioCraft[v2.4.2][MC1.12.0].jar) 
	UCHI	bookshelf{2.0.412} [Bookshelf] (Bookshelf-1.12-2.0.0.412.jar) 
	UCHI	ceramics{1.12-1.3.1} [Ceramics] (Ceramics-1.12-1.3.1.jar) 
	UCHI	chameleon{1.12-4.1.0} [Chameleon] (Chameleon-1.12-4.1.0.jar) 
	UCHI	codechickenlib{3.1.0.278} [CodeChicken Lib] (CodeChickenLib-1.12-3.1.0.278-universal.jar) 
	UCHI	redstoneflux{2.0.0} [Redstone Flux] (RedstoneFlux-1.12-2.0.0.1-universal.jar) 
	UCHI	cofhcore{4.3.1} [CoFH Core] (CoFHCore-1.12-4.3.1.6-universal.jar) 
	UCHI	cofhworld{1.0.0} [CoFH World] (CoFHWorld-1.12-1.0.0.5-universal.jar) 
	UCHI	cyclopscore{0.10.7} [Cyclops Core] (CyclopsCore-1.12-0.10.7.jar) 
	UCHI	commoncapabilities{1.3.3} [CommonCapabilities] (CommonCapabilities-1.12-1.3.3.jar) 
	UCHI	waila{1.8.19} [Waila] (Hwyla-1.8.19-B33_1.12.jar) 
	UCHI	darkutils{${version}} [Dark Utilities] (DarkUtils-1.12-1.6.156.jar) 
	UCHI	elevatorid{1.3.4} [Elevator Mod] (ElevatorMod-1.12-1.3.4.jar) 
	UCHI	enderutilities{0.7.1} [Ender Utilities] (enderutilities-1.12.0-0.7.1.jar) 
	UCHI	zerocore{1.12-0.1.0.9} [Zero CORE] (zerocore-1.12-0.1.0.9.jar) 
	UCHI	bigreactors{1.12-0.4.5.33} [Extreme Reactors] (ExtremeReactors-1.12-0.4.5.33.jar) 
	UCHI	forgelin{1.4.2} [Shadowfacts' Forgelin] (Forgelin-1.5.0.jar) 
	UCHI	ftbl{0.0.0} [FTBLib] (FTBLib-4.0.5.jar) 
	UCHI	ftbu{0.0.0} [FTBUtilities] (FTBUtilities-4.0.3.jar) 
	UCHI	glass_shards{1.7} [Glass Shards] (glass_shards_mc1.12-1.7.jar) 
	UCHI	gravestone{1.8.4} [Gravestone Mod] (gravestone-1.8.4.jar) 
	UCHI	inventorytweaks{1.63+dev.98.684f99a} [Inventory Tweaks] (InventoryTweaks-1.63+dev.98.jar) 
	UCHI	ironchest{1.12-7.0.31.818} [Iron Chest] (ironchest-1.12-7.0.31.818.jar) 
	UCHI	journeymap{1.12-5.4.9} [JourneyMap] (journeymap-1.12-5.4.9.jar) 
	UCHI	mantle{1.12-1.3.0.8} [Mantle] (Mantle-1.12-1.3.0.8.jar) 
	UCHI	morpheus{1.12-3.3.2} [Morpheus] (Morpheus-1.12-3.3.2.jar) 
	UCHI	mysticalagriculture{1.6.1} [Mystical Agriculture] (mysticalagriculture[1.12]-1.6.1a.jar) 
	UCHI	mysticalagradditions{1.2.0} [Mystical Agradditions] (mysticalagradditions[1.12]-1.2.0.jar) 
	UCHI	natura{1.12-4.3.0.10} [Natura] (Natura-1.12-4.3.0.10.jar) 
	UCHI	netherportalfix{1.0} [NetherPortalFix] (NetherPortalFix_1.12-5.3.1.jar) 
	UCHI	nmsot{1.2.1-mc1.12} [No Mob Spawning on Trees] (NoMobSpawningOnTrees-1.2.1-mc1.12.jar) 
	UCHI	notenoughwands{1.5.9} [Not Enough Wands] (notenoughwands-1.12-1.5.9.jar) 
	UCHI	shetiphiancore{3.5.0.1} [ShetiPhian-Core] (shetiphiancore-1.12.0-3.5.0.1.jar) 
	UCHI	platforms{1.4.0.1} [Platforms] (platforms-1.12.0-1.4.0.1.jar) 
	UCHI	reborncore{3.2.3.83} [Reborn Core] (RebornCore-1.12-3.2.3.83-universal.jar) 
	UCHI	quantumstorage{4.3.4} [QuantumStorage] (QuantumStorage-1.12-4.3.4.jar) 
	UCHI	quickleafdecay{1.2.3} [Quick Leaf Decay] (QuickLeafDecay-MC1.12-1.2.3.jar) 
	UCHI	randomthings{4.0.2} [Random Things] (RandomThings-MC1.12-4.0.2.jar) 
	UCHI	rangedpumps{0.5} [Ranged Pumps] (rangedpumps-0.5.jar) 
	UCHI	thermalfoundation{2.3.1} [Thermal Foundation] (ThermalFoundation-1.12-2.3.1.5-universal.jar) 
	UCHI	thermalexpansion{5.3.1} [Thermal Expansion] (ThermalExpansion-1.12-5.3.1.6-universal.jar) 
	UCHI	redstonearsenal{2.3.1} [Redstone Arsenal] (RedstoneArsenal-1.12-2.3.1.5-universal.jar) 
	UCHI	storagedrawers{1.12-5.2.2} [Storage Drawers] (StorageDrawers-1.12-5.2.2.jar) 
	UCHI	refinedstorage{1.5.8} [Refined Storage] (refinedstorage-1.5.8.jar) 
	UCHI	rflux{0.1.1} [RF Lux] (rflux-1.12-0.1.1.jar) 
	UCHI	rftools{6.10} [RFTools] (rftools-1.12-6.10beta3.jar) 
	UCHI	rftoolscontrol{1.6.8} [RFTools Control] (rftoolsctrl-1.12-1.6.8beta1.jar) 
	UCHI	rftoolsdim{5.02} [RFTools Dimensions] (rftoolsdim-1.12-5.02beta1.jar) 
	UCHI	tammodized{0.13.4} [TamModized] (TamModized-1.12-0.13.4.jar) 
	UCHI	tesla{1.0.61} [TESLA] (Tesla-1.12-1.0.61.jar) 
	UCHI	teslacorelib{@@VERSION@@} [Tesla Core Lib] (tesla-core-lib-1.12-1.0.1.jar) 
	UCHE	teslathingies{1.12-1.0.1} [Tesla Powered Thingies] (teslathingies-1.12-1.0.1.jar) 
	UCHI	thermaldynamics{2.3.1} [Thermal Dynamics] (ThermalDynamics-1.12-2.3.1.6-universal.jar) 
	UCHI	tickprofiler{1.12-jenkins.12} [TickProfiler] (TickProfiler-1.12-jenkins.12.jar) 
	UCHI	unifieditems{1.6.3.186} [Unified Items] (UnifiedItems-1.12-1.6.3-186.jar) 
	UCHI	voidcraft{0.21.2} [VoidCraft] (VoidCraft-1.12-0.21.2.jar) 
	UCHI	wawla{2.5.239} [What Are We Looking At] (Wawla-1.12-2.5.239.jar) 
	UCHI	xnet{1.3.4.3} [XNet] (xnet-1.12-1.3.4.3.jar) 
	UCHI	yabba{1.12-0.5.3} [YABBA] (YABBA-1.12-0.5.3.jar) 
	UCHI	teslacoreregistries{@@VERSION@@} [Tesla Core Registries] (tesla-core-lib-1.12-1.0.1.jar) 
	Loaded coremods (and transformers): 
ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.0.1.jar)
  shetiphian.asm.ClassTransformer
LibLoader (# LibLoader.jar)
  
FullscreenFix (gud_fullscreen_fix-1.0.2 (1).jar)
  net.gudenau.fullscreenfix.Transformer
AppleCore (AppleCore-mc1.12-2.2.1.jar)
  squeek.applecore.asm.TransformerModuleHandler
CoreMod (TickProfiler-1.12-jenkins.12.jar)
  
ForgelinPlugin (Forgelin-1.5.0.jar)
  
LoadingPlugin (Quark-r1.2-100.jar)
  vazkii.quark.base.asm.ClassTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63+dev.98.jar)
  invtweaks.forge.asm.ContainerTransformer
LoadingPlugin (RandomThings-MC1.12-4.0.2.jar)
  lumien.randomthings.asm.ClassTransformer
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	codechickenlib Invalid Fingerprint Reports: - No invalid fingerprints.: 
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.2.3.83
		Runtime Debofucsation 1
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by ImAK9** [comment] 2017-07-08 15:34
Got the same one...
https://pastebin.com/K60CEtC2

**Comment by faceofcat** [comment] 2017-07-08 15:37
I probably know what the problem is... but I can't fix it until tomorrow
night when I get back to my computer... :(

sorry...

**Comment by tiarnia** [comment] 2017-07-08 15:37
the client loads fine weird and i can play single player

**Comment by tiarnia** [comment] 2017-07-08 15:38
that's fast enough for me ^^

**Comment by ImAK9** [comment] 2017-07-08 15:44
Forge changed a method with proxies that's why this problem occured.

**Comment by ImAK9** [comment] 2017-07-08 15:45
It's trying to use a Client method in server proxy i think..

**Comment by faceofcat** [comment] 2017-07-09 20:19
fixed in [Tesla Core Lib : 1.12 - 1.0.2](https://minecraft.curseforge.com/projects/tesla-core-lib/files/2448217)

**Closed as completed by faceofcat** 2017-07-09 20:19 UTC
Labels: bug
