### ISSUE TITLE
Machines don't realise there powered.

### ISSUE THREAD

**Issue by Larky2k** [faceofcat/Tesla-Powered-Thingies#38] opened 2018-01-13 13:27 UTC
When i connect power to any of the machines and configure them it takes anywhere from a minute to 10 minutes for the machines to realise they have power and start working. Also any chance for an Auto Eject feature so it ejects into the adjacent block (if this feature is already in then it not working).

**Comment by faceofcat** [comment] 2018-01-13 13:40
what are you using to power the machines?

**Comment by Larky2k** [comment] 2018-01-13 14:18
Immersive Engineering at the moment. It works but takes an age for the machines to realise they have power.

**Comment by faceofcat** [comment] 2018-01-13 14:22
did you configure my machine first and then place the IE thing on it?... or did you place the IE thing on it and then configured my machine?

**Comment by faceofcat** [comment] 2018-01-13 14:23
try configuring my machine and then placing the IE thing...

the thing about "incoming" power is that I do nothing :)... other tile entities power my machines... it's not like I'm extracting power from anywhere.

**Comment by Larky2k** [comment] 2018-01-13 14:25
ok if you configure first then place down relay it works but if you do it the other way then there is an annoying delay.

**Comment by faceofcat** [comment] 2018-01-13 14:27
blame IE :)
they probably don't recheck nearby tile entities on the "block update event"... (can't remember it's exact name)

**Comment by Larky2k** [comment] 2018-01-13 14:28
ok will pass that on to IE, Also will you be adding an Auto Eject feature to the machines so you can eject into a Chest or another machine.

**Comment by faceofcat** [comment] 2018-01-13 14:30
this is actually a duplicate of faceofcat/Tesla-Core-Lib#22

if you are going to report this to IE link that tesla core lib issue to them... there is more info there.

**Closed as completed by faceofcat** 2018-01-13 14:30 UTC
